spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    url: jdbc:mysql://localhost:3306/onePic?serverTimezone=UTC
    username: root
    password: root

onePic:
  picStoragePath: D:\\tmp
  nginxRequestPath: https://www.cccsp.cc:9090/webimg/


