# 应用名称
spring:
  profiles:
    active: dev
  application:
    name: yiyan

# 应用端口
server:
  port: 9002

mybatis-plus:
  global-config:
    db-config:
      # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-field: isDelete
      # 逻辑已删除值(默认为 1)
      logic-delete-value: 1
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: 0
  # 打印sql
  configuration.log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

