# \u5E94\u7528\u540D\u79F0
spring:
  profiles:
    active: prod
  application:
    name: yiyan

# \u5E94\u7528\u670D\u52A1 WEB \u8BBF\u95EE\u7AEF\u53E3
server:
  port: 9001

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDelete # \u5168\u5C40\u903B\u8F91\u5220\u9664\u7684\u5B9E\u4F53\u5B57\u6BB5\u540D(since 3.3.0,\u914D\u7F6E\u540E\u53EF\u4EE5\u5FFD\u7565\u4E0D\u914D\u7F6E\u6B65\u9AA42)
      logic-delete-value: 1 # \u903B\u8F91\u5DF2\u5220\u9664\u503C(\u9ED8\u8BA4\u4E3A 1)
      logic-not-delete-value: 0 # \u903B\u8F91\u672A\u5220\u9664\u503C(\u9ED8\u8BA4\u4E3A 0)
  #\u5F00\u542Fsql\u65E5\u5FD7
  configuration.log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

